name: Continuous integration
on: [push, pull_request]

jobs:
  check:
    name: Build and check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          version: ^11
          runtime: node@26
          cache: true

      - name: Build code
        run: pnpm build

      - name: Check code
        run: pnpm check

      - name: Format code
        run: pnpm fmt:check
